# Generated by Django 4.2 on 2023-04-30 19:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Clients',
            fields=[
                ('clientId', models.IntegerField(primary_key=True, serialize=False, verbose_name='clientId')),
                ('last_name', models.CharField(max_length=100, verbose_name='last_name')),
                ('first_name', models.CharField(max_length=100, verbose_name='first_name')),
                ('full_name', models.CharField(max_length=100, verbose_name='full_name')),
                ('gender', models.CharField(choices=[('м', 'муж'), ('ж', 'жен')], default='ж', max_length=1, verbose_name='gender')),
                ('phone', models.CharField(max_length=13, verbose_name='phone')),
                ('remark', models.CharField(max_length=200, null=True, verbose_name='remark')),
            ],
        ),
    ]
