# Generated by Django 4.2 on 2023-04-30 20:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CyberClass', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='clients',
            name='clientId',
        ),
        migrations.AddField(
            model_name='clients',
            name='id',
            field=models.BigAutoField(auto_created=True, default=1, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
    ]
