# Generated by Django 4.2 on 2023-05-07 14:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CyberClass', '0003_services_alter_clients_first_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='services',
            name='service_duration',
            field=models.IntegerField(max_length=100, verbose_name='Длительность (в минутах)'),
        ),
    ]
