# Generated by Django 4.2 on 2023-05-07 14:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CyberClass', '0004_alter_services_service_duration'),
    ]

    operations = [
        migrations.AlterField(
            model_name='services',
            name='service_duration',
            field=models.IntegerField(verbose_name='Длительность (в минутах)'),
        ),
    ]
