# Generated by Django 4.2 on 2023-05-08 20:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('CyberClass', '0005_alter_services_service_duration'),
    ]

    operations = [
        migrations.CreateModel(
            name='Deals',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_deals', models.DateField()),
                ('id_client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='CyberClass.clients')),
                ('id_service', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='CyberClass.services')),
            ],
        ),
    ]
