# Generated by Django 4.2 on 2023-05-18 12:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CyberClass', '0007_employees'),
    ]

    operations = [
        migrations.AddField(
            model_name='employees',
            name='role',
            field=models.CharField(choices=[('Администратор', 'Администратор'), ('Директор', 'Директор')], default='Администратор', max_length=15, verbose_name='Роль'),
        ),
    ]
